import type {
  SupplierCatalogWorld,
  SupplierConnectionFixture,
  SupplierProductFixture,
} from '@/lib/products/catalog-types';

/**
 * Typed fixture data for the "All Supplier Products" redesign preview.
 *
 * Every image is `null` on purpose: CJ and AliExpress thumbnails are only
 * ever allowed through `next/image` from allow-listed CDN hosts
 * (`next.config.ts`), and inventing a fake external host here would either
 * break the build's remote-pattern check or (worse) quietly train the
 * component to accept an unlisted host. The existing placeholder tile
 * (`CjProductRow`'s pattern) already covers "no image" honestly, so the
 * prototype reuses that instead of a fabricated picture.
 *
 * `sourceUrl` strings are illustrative supplier-URL shapes, shown as plain
 * text in the details drawer - never rendered as a clickable outbound link,
 * since nothing here is a real fetched page.
 *
 * CJ quotes in USD, AliExpress here quotes in AUD - both resolve to a live
 * PHP estimate via `resolveCatalogFxRates()` (see `fx-preview.ts`). Money is
 * still in integer minor units throughout.
 */

const CJ_CONNECTION: Omit<SupplierConnectionFixture, 'status'> = {
  id: 'conn-cj',
  providerCode: 'CJ_DROPSHIPPING',
  providerDisplayName: 'CJ Dropshipping',
  providerLogoInitial: 'CJ',
  connectedAccountLabel: 'CJ Dropshipping (Sals3 Official)',
  lastVerifiedAt: '2026-08-08T01:10:00.000Z',
};

const ALIEXPRESS_CONNECTION: Omit<SupplierConnectionFixture, 'status'> = {
  id: 'conn-aliexpress',
  providerCode: 'ALIEXPRESS',
  providerDisplayName: 'AliExpress',
  providerLogoInitial: 'AE',
  connectedAccountLabel: 'AliExpress (Sals3 Official)',
  lastVerifiedAt: '2026-08-08T00:55:00.000Z',
};

function connection(
  base: Omit<SupplierConnectionFixture, 'status'>,
  status: SupplierConnectionFixture['status'],
): SupplierConnectionFixture {
  return { ...base, status };
}

/**
 * The full product pool, tagged by which connection sources it. One world
 * (`multi-healthy`) shows all of them; other worlds filter down to whichever
 * connections are active in that world, matching what the real page would do
 * when a connection stops qualifying as an active catalog filter.
 *
 * Covers every fixture case design section 19 asked for: PASS, PASS with
 * attention, blocked, evaluating, not-yet-queued, evaluation failed, queued,
 * mixed currencies, partial variant stock, no shipping route, a
 * cross-supplier duplicate pair, stale evidence, one existing listing, and
 * multiple existing listings.
 */
const PRODUCTS: SupplierProductFixture[] = [
  {
    id: 'cj-tumbler',
    eligibleMarkets: ['PH', 'SG'],
    connectionId: 'conn-cj',
    externalProductId: 'CJYD3041882',
    externalVariantIds: ['v-1', 'v-2', 'v-3'],
    title: 'Insulated Stainless Steel Tumbler 500ml',
    normalizedTitle: 'Insulated Steel Tumbler (500ml)',
    imageUrl: null,
    category: 'Drinkware',
    supplierCurrency: 'USD',
    supplierPriceMinor: 409,
    supplierPriceMaxMinor: 529,
    stock: 'IN_STOCK',
    availableVariantCount: 3,
    totalVariantCount: 3,
    shipsFrom: ['CN', 'CN_US'],
    evaluationStatus: 'PASS',
    evaluationReasonCodes: [],
    lastSupplierUpdateAt: '2026-08-07T09:00:00.000Z',
    lastSyncedAt: '2026-08-08T01:05:00.000Z',
    isStale: false,
    existingListingsCount: 0,
    potentialDuplicateOfIds: [],
    mediaRightsWarning: false,
    restrictedCategoryWarning: false,
    sourceUrl: 'https://cjdropshipping.com/product/-p-CJYD3041882.html',
  },
  {
    id: 'cj-resistance-band',
    eligibleMarkets: ['PH'],
    connectionId: 'conn-cj',
    externalProductId: 'CJYD3044514',
    externalVariantIds: ['v-4', 'v-5'],
    title: '8-Character Resistance Band For Shoulder Opening',
    normalizedTitle: null,
    imageUrl: null,
    category: 'Fitness',
    supplierCurrency: 'USD',
    supplierPriceMinor: 177,
    supplierPriceMaxMinor: null,
    stock: 'PARTIAL_VARIANT_STOCK',
    availableVariantCount: 1,
    totalVariantCount: 2,
    shipsFrom: ['CN'],
    evaluationStatus: 'PASS_WITH_ATTENTION',
    evaluationReasonCodes: ['LOW_MARGIN_ESTIMATE'],
    lastSupplierUpdateAt: '2026-08-07T11:00:00.000Z',
    lastSyncedAt: '2026-08-08T01:05:00.000Z',
    isStale: false,
    existingListingsCount: 1,
    potentialDuplicateOfIds: [],
    mediaRightsWarning: false,
    restrictedCategoryWarning: false,
    sourceUrl: 'https://cjdropshipping.com/product/-p-CJYD3044514.html',
  },
  {
    id: 'cj-blocked-item',
    eligibleMarkets: [],
    connectionId: 'conn-cj',
    externalProductId: 'CJBQ3040119',
    externalVariantIds: ['v-6'],
    title: 'Branded-Replica Wireless Earbuds Case',
    normalizedTitle: null,
    imageUrl: null,
    category: 'Electronics Accessories',
    supplierCurrency: 'USD',
    supplierPriceMinor: 890,
    supplierPriceMaxMinor: null,
    stock: 'UNKNOWN',
    availableVariantCount: null,
    totalVariantCount: 1,
    shipsFrom: ['CN'],
    evaluationStatus: 'BLOCKED',
    evaluationReasonCodes: ['COUNTERFEIT_HIGH_CONFIDENCE'],
    lastSupplierUpdateAt: '2026-08-06T08:00:00.000Z',
    lastSyncedAt: '2026-08-08T01:05:00.000Z',
    isStale: false,
    existingListingsCount: 0,
    potentialDuplicateOfIds: [],
    mediaRightsWarning: false,
    restrictedCategoryWarning: true,
    sourceUrl: 'https://cjdropshipping.com/product/-p-CJBQ3040119.html',
  },
  {
    id: 'cj-evaluating-item',
    eligibleMarkets: ['PH', 'ID', 'SG'],
    connectionId: 'conn-cj',
    externalProductId: 'CJJT3044643',
    externalVariantIds: ['v-7'],
    title: 'People Use Camping Charcoal Barbecue Ovens',
    normalizedTitle: null,
    imageUrl: null,
    category: 'Home Office Storage',
    supplierCurrency: 'USD',
    supplierPriceMinor: 3299,
    supplierPriceMaxMinor: null,
    stock: 'IN_STOCK',
    availableVariantCount: 1,
    totalVariantCount: 1,
    shipsFrom: ['CN', 'CN_US'],
    evaluationStatus: 'EVALUATING',
    evaluationReasonCodes: [],
    lastSupplierUpdateAt: '2026-08-07T22:00:00.000Z',
    lastSyncedAt: '2026-08-08T01:05:00.000Z',
    isStale: false,
    existingListingsCount: 0,
    potentialDuplicateOfIds: [],
    mediaRightsWarning: false,
    restrictedCategoryWarning: false,
    sourceUrl: 'https://cjdropshipping.com/product/-p-CJJT3044643.html',
  },
  {
    id: 'cj-not-yet-queued',
    eligibleMarkets: ['PH'],
    connectionId: 'conn-cj',
    externalProductId: 'CJYD3044588',
    externalVariantIds: ['v-8'],
    title: 'Woodworkers Pencil Double-Ended Large Octagonal',
    normalizedTitle: null,
    imageUrl: null,
    category: 'Home Office Storage',
    supplierCurrency: 'USD',
    supplierPriceMinor: 52,
    supplierPriceMaxMinor: null,
    stock: 'OUT_OF_STOCK',
    availableVariantCount: 0,
    totalVariantCount: 1,
    shipsFrom: ['CN', 'CN_US'],
    evaluationStatus: null,
    evaluationReasonCodes: [],
    lastSupplierUpdateAt: '2026-08-07T09:30:00.000Z',
    lastSyncedAt: '2026-08-08T01:05:00.000Z',
    isStale: false,
    existingListingsCount: 0,
    potentialDuplicateOfIds: [],
    mediaRightsWarning: false,
    restrictedCategoryWarning: false,
    sourceUrl: 'https://cjdropshipping.com/product/-p-CJYD3044588.html',
  },
  {
    id: 'cj-evaluation-failed',
    eligibleMarkets: [],
    connectionId: 'conn-cj',
    externalProductId: 'CJYD3039201',
    externalVariantIds: ['v-9'],
    title: 'Solar-Powered Garden Path Lights (4-Pack)',
    normalizedTitle: null,
    imageUrl: null,
    category: 'Outdoor Lighting',
    supplierCurrency: 'USD',
    supplierPriceMinor: 1249,
    supplierPriceMaxMinor: null,
    stock: 'UNKNOWN',
    availableVariantCount: null,
    totalVariantCount: null,
    shipsFrom: ['CN'],
    evaluationStatus: 'EVALUATION_FAILED',
    evaluationReasonCodes: ['DATA_FETCH_FAILED'],
    lastSupplierUpdateAt: '2026-08-05T14:00:00.000Z',
    lastSyncedAt: '2026-08-08T01:05:00.000Z',
    isStale: true,
    existingListingsCount: 0,
    potentialDuplicateOfIds: [],
    mediaRightsWarning: false,
    restrictedCategoryWarning: false,
    sourceUrl: 'https://cjdropshipping.com/product/-p-CJYD3039201.html',
  },
  {
    id: 'cj-no-shipping-route',
    eligibleMarkets: [],
    connectionId: 'conn-cj',
    externalProductId: 'CJLX3042177',
    externalVariantIds: ['v-10'],
    title: 'Titanium Steel Non-Fading Letter Necklace',
    normalizedTitle: null,
    imageUrl: null,
    category: 'Necklace & Pendants',
    supplierCurrency: 'USD',
    supplierPriceMinor: 555,
    supplierPriceMaxMinor: null,
    stock: 'OUT_OF_STOCK',
    availableVariantCount: 0,
    totalVariantCount: 4,
    shipsFrom: [],
    evaluationStatus: 'TEMPORARILY_INELIGIBLE',
    evaluationReasonCodes: ['NO_SHIPPING_ROUTE'],
    lastSupplierUpdateAt: '2026-08-07T06:00:00.000Z',
    lastSyncedAt: '2026-08-08T01:05:00.000Z',
    isStale: false,
    existingListingsCount: 0,
    potentialDuplicateOfIds: [],
    mediaRightsWarning: false,
    restrictedCategoryWarning: false,
    sourceUrl: 'https://cjdropshipping.com/product/-p-CJLX3042177.html',
  },
  {
    id: 'cj-stale-evidence',
    eligibleMarkets: ['PH'],
    connectionId: 'conn-cj',
    externalProductId: 'CJYD2998104',
    externalVariantIds: ['v-11'],
    title: 'Foldable Laundry Hamper With Lid',
    normalizedTitle: null,
    imageUrl: null,
    category: 'Home Office Storage',
    supplierCurrency: 'USD',
    supplierPriceMinor: 899,
    supplierPriceMaxMinor: null,
    stock: 'IN_STOCK',
    availableVariantCount: 2,
    totalVariantCount: 2,
    shipsFrom: ['CN', 'CN_US'],
    evaluationStatus: 'PASS',
    evaluationReasonCodes: [],
    lastSupplierUpdateAt: '2026-07-29T10:00:00.000Z',
    lastSyncedAt: '2026-07-31T04:00:00.000Z',
    isStale: true,
    existingListingsCount: 0,
    potentialDuplicateOfIds: [],
    mediaRightsWarning: false,
    restrictedCategoryWarning: false,
    sourceUrl: 'https://cjdropshipping.com/product/-p-CJYD2998104.html',
  },
  {
    id: 'cj-multiple-listings',
    eligibleMarkets: ['PH', 'SG'],
    connectionId: 'conn-cj',
    externalProductId: 'CJYD3012456',
    externalVariantIds: ['v-12', 'v-13'],
    title: 'Ceramic Pour-Over Coffee Dripper Set',
    normalizedTitle: 'Pour-Over Coffee Dripper Set',
    imageUrl: null,
    category: 'Drinkware',
    supplierCurrency: 'USD',
    supplierPriceMinor: 1150,
    supplierPriceMaxMinor: 1450,
    stock: 'IN_STOCK',
    availableVariantCount: 2,
    totalVariantCount: 2,
    shipsFrom: ['CN', 'CN_US'],
    evaluationStatus: 'PASS',
    evaluationReasonCodes: [],
    lastSupplierUpdateAt: '2026-08-06T12:00:00.000Z',
    lastSyncedAt: '2026-08-08T01:05:00.000Z',
    isStale: false,
    existingListingsCount: 3,
    potentialDuplicateOfIds: [],
    mediaRightsWarning: false,
    restrictedCategoryWarning: false,
    sourceUrl: 'https://cjdropshipping.com/product/-p-CJYD3012456.html',
  },
  {
    id: 'cj-duplicate-a',
    eligibleMarkets: ['PH'],
    connectionId: 'conn-cj',
    externalProductId: 'CJYD3050091',
    externalVariantIds: ['v-14'],
    title: 'Mini Handheld Milk Frother Whisk',
    normalizedTitle: null,
    imageUrl: null,
    category: 'Kitchen Tools',
    supplierCurrency: 'USD',
    supplierPriceMinor: 299,
    supplierPriceMaxMinor: null,
    stock: 'IN_STOCK',
    availableVariantCount: 1,
    totalVariantCount: 1,
    shipsFrom: ['CN', 'CN_US'],
    evaluationStatus: 'PASS',
    evaluationReasonCodes: [],
    lastSupplierUpdateAt: '2026-08-07T15:00:00.000Z',
    lastSyncedAt: '2026-08-08T01:05:00.000Z',
    isStale: false,
    existingListingsCount: 0,
    potentialDuplicateOfIds: ['ali-duplicate-b'],
    mediaRightsWarning: false,
    restrictedCategoryWarning: false,
    sourceUrl: 'https://cjdropshipping.com/product/-p-CJYD3050091.html',
  },
  {
    id: 'cj-queued-item',
    eligibleMarkets: ['PH'],
    connectionId: 'conn-cj',
    externalProductId: 'CJYD3051002',
    externalVariantIds: ['v-15'],
    title: 'Bamboo Desk Organizer With Drawer',
    normalizedTitle: null,
    imageUrl: null,
    category: 'Home Office Storage',
    supplierCurrency: 'USD',
    supplierPriceMinor: 640,
    supplierPriceMaxMinor: null,
    stock: 'IN_STOCK',
    availableVariantCount: 1,
    totalVariantCount: 1,
    shipsFrom: ['CN'],
    evaluationStatus: 'QUEUED',
    evaluationReasonCodes: [],
    lastSupplierUpdateAt: '2026-08-08T00:40:00.000Z',
    lastSyncedAt: '2026-08-08T01:05:00.000Z',
    isStale: false,
    existingListingsCount: 0,
    potentialDuplicateOfIds: [],
    mediaRightsWarning: false,
    restrictedCategoryWarning: false,
    sourceUrl: 'https://cjdropshipping.com/product/-p-CJYD3051002.html',
  },
  {
    id: 'ali-duplicate-b',
    eligibleMarkets: ['PH'],
    connectionId: 'conn-aliexpress',
    externalProductId: '1005006712345678',
    externalVariantIds: ['ae-v-1'],
    title: 'Handheld Electric Milk Frother Mixer',
    normalizedTitle: null,
    imageUrl: null,
    category: 'Kitchen Tools',
    supplierCurrency: 'AUD',
    supplierPriceMinor: 490,
    supplierPriceMaxMinor: null,
    stock: 'IN_STOCK',
    availableVariantCount: 3,
    totalVariantCount: 3,
    shipsFrom: ['CN'],
    evaluationStatus: 'PASS',
    evaluationReasonCodes: [],
    lastSupplierUpdateAt: '2026-08-07T13:00:00.000Z',
    lastSyncedAt: '2026-08-08T00:50:00.000Z',
    isStale: false,
    existingListingsCount: 0,
    potentialDuplicateOfIds: ['cj-duplicate-a'],
    mediaRightsWarning: false,
    restrictedCategoryWarning: false,
    sourceUrl: 'https://aliexpress.com/item/1005006712345678.html',
  },
  {
    id: 'ali-attention-item',
    eligibleMarkets: ['PH', 'ID'],
    connectionId: 'conn-aliexpress',
    externalProductId: '1005005998877665',
    externalVariantIds: ['ae-v-2', 'ae-v-3'],
    title: 'Retro Film-Style Instant Print Sticker Paper',
    normalizedTitle: null,
    imageUrl: null,
    category: 'Stickers',
    supplierCurrency: 'AUD',
    supplierPriceMinor: 390,
    supplierPriceMaxMinor: 490,
    stock: 'PARTIAL_VARIANT_STOCK',
    availableVariantCount: 1,
    totalVariantCount: 2,
    shipsFrom: ['CN'],
    evaluationStatus: 'PASS_WITH_ATTENTION',
    evaluationReasonCodes: ['MEDIA_RIGHTS_UNCONFIRMED'],
    lastSupplierUpdateAt: '2026-08-07T10:00:00.000Z',
    lastSyncedAt: '2026-08-08T00:50:00.000Z',
    isStale: false,
    existingListingsCount: 0,
    potentialDuplicateOfIds: [],
    mediaRightsWarning: true,
    restrictedCategoryWarning: false,
    sourceUrl: 'https://aliexpress.com/item/1005005998877665.html',
  },
  {
    id: 'ali-not-yet-queued',
    eligibleMarkets: ['PH'],
    connectionId: 'conn-aliexpress',
    externalProductId: '1005004556677889',
    externalVariantIds: ['ae-v-4'],
    title: 'Magnetic Cable Organizer Clips (Set of 6)',
    normalizedTitle: null,
    imageUrl: null,
    category: 'Cable Management',
    supplierCurrency: 'AUD',
    supplierPriceMinor: 290,
    supplierPriceMaxMinor: null,
    stock: 'IN_STOCK',
    availableVariantCount: 1,
    totalVariantCount: 1,
    shipsFrom: ['CN'],
    evaluationStatus: null,
    evaluationReasonCodes: [],
    lastSupplierUpdateAt: '2026-08-07T18:00:00.000Z',
    lastSyncedAt: '2026-08-08T00:50:00.000Z',
    isStale: false,
    existingListingsCount: 0,
    potentialDuplicateOfIds: [],
    mediaRightsWarning: false,
    restrictedCategoryWarning: false,
    sourceUrl: 'https://aliexpress.com/item/1005004556677889.html',
  },
  {
    id: 'ali-blocked-item',
    eligibleMarkets: [],
    connectionId: 'conn-aliexpress',
    externalProductId: '1005003112233445',
    externalVariantIds: ['ae-v-5'],
    title: 'Unbranded "Designer-Style" Belt Buckle',
    normalizedTitle: null,
    imageUrl: null,
    category: 'Belts',
    supplierCurrency: 'AUD',
    supplierPriceMinor: 690,
    supplierPriceMaxMinor: null,
    stock: 'UNKNOWN',
    availableVariantCount: null,
    totalVariantCount: null,
    shipsFrom: ['CN'],
    evaluationStatus: 'BLOCKED',
    evaluationReasonCodes: ['COUNTERFEIT_HIGH_CONFIDENCE'],
    lastSupplierUpdateAt: '2026-08-04T09:00:00.000Z',
    lastSyncedAt: '2026-08-08T00:50:00.000Z',
    isStale: false,
    existingListingsCount: 0,
    potentialDuplicateOfIds: [],
    mediaRightsWarning: false,
    restrictedCategoryWarning: true,
    sourceUrl: 'https://aliexpress.com/item/1005003112233445.html',
  },
];

function productsFor(connectionIds: string[]): SupplierProductFixture[] {
  const ids = new Set(connectionIds);

  return PRODUCTS.filter((product) => ids.has(product.connectionId));
}

/**
 * One "world" per required design state (spec section 10's list plus the
 * no-connection and single-connection cases). Selected in the preview page
 * via `?scenario=`, so every required state is reachable from one running
 * route instead of needing a screenshot per case.
 */
export const CATALOG_WORLDS: Record<string, SupplierCatalogWorld> = {
  'multi-healthy': {
    key: 'multi-healthy',
    label: 'Multiple healthy suppliers',
    description: 'CJ Dropshipping and AliExpress both connected and healthy.',
    connections: [
      connection(CJ_CONNECTION, 'CONNECTED'),
      connection(ALIEXPRESS_CONNECTION, 'CONNECTED'),
    ],
    fetchFailures: [],
    products: productsFor(['conn-cj', 'conn-aliexpress']),
  },
  'single-supplier': {
    key: 'single-supplier',
    label: 'One healthy supplier',
    description: 'Only CJ Dropshipping is connected.',
    connections: [connection(CJ_CONNECTION, 'CONNECTED')],
    fetchFailures: [],
    products: productsFor(['conn-cj']),
  },
  degraded: {
    key: 'degraded',
    label: 'One degraded supplier',
    description:
      'CJ is healthy; AliExpress connection is degraded (results may be stale or incomplete).',
    connections: [
      connection(CJ_CONNECTION, 'CONNECTED'),
      connection(ALIEXPRESS_CONNECTION, 'DEGRADED'),
    ],
    fetchFailures: [],
    products: productsFor(['conn-cj', 'conn-aliexpress']),
  },
  'partial-failure': {
    key: 'partial-failure',
    label: 'One supplier temporarily unavailable',
    description:
      'CJ is healthy; AliExpress could not be refreshed on this load.',
    connections: [
      connection(CJ_CONNECTION, 'CONNECTED'),
      connection(ALIEXPRESS_CONNECTION, 'CONNECTED'),
    ],
    fetchFailures: [
      {
        connectionId: 'conn-aliexpress',
        lastSuccessfulSyncAt: '2026-08-07T19:20:00.000Z',
      },
    ],
    products: productsFor(['conn-cj']),
  },
  'reauth-required': {
    key: 'reauth-required',
    label: 'Supplier requires reconnection',
    description: 'AliExpress needs to be re-authenticated under Supplier Apps.',
    connections: [
      connection(CJ_CONNECTION, 'CONNECTED'),
      connection(ALIEXPRESS_CONNECTION, 'REAUTH_REQUIRED'),
    ],
    fetchFailures: [],
    products: productsFor(['conn-cj']),
  },
  'all-unavailable': {
    key: 'all-unavailable',
    label: 'All suppliers unavailable',
    description: 'Every active connection failed to refresh on this load.',
    connections: [
      connection(CJ_CONNECTION, 'CONNECTED'),
      connection(ALIEXPRESS_CONNECTION, 'CONNECTED'),
    ],
    fetchFailures: [
      {
        connectionId: 'conn-cj',
        lastSuccessfulSyncAt: '2026-08-07T20:10:00.000Z',
      },
      {
        connectionId: 'conn-aliexpress',
        lastSuccessfulSyncAt: '2026-08-07T19:20:00.000Z',
      },
    ],
    products: [],
  },
  'no-suppliers': {
    key: 'no-suppliers',
    label: 'No active supplier apps',
    description: 'The seller has not connected any supplier account yet.',
    connections: [],
    fetchFailures: [],
    products: [],
  },
};

export const DEFAULT_WORLD_KEY = 'multi-healthy';

export function getWorld(key: string | undefined): SupplierCatalogWorld {
  if (key !== undefined && key in CATALOG_WORLDS) {
    return CATALOG_WORLDS[key];
  }

  return CATALOG_WORLDS[DEFAULT_WORLD_KEY];
}
