export const SALS3_CATEGORY_L1_OPTIONS = [
  'Home, Furniture & Living',
  'Sports, Fitness & Outdoor Gear',
  'Beauty & Personal Care',
  'Food, Beverage & Gourmet',
  "Children's & Infant Fashion",
  'Maternity & Baby Care',
  'Home & Kitchen Appliances',
  "Women's Apparel & Fashion",
  'Office Supplies & Stationery',
  'Computers, Laptops & IT Equipment',
  'Automotive Parts & Accessories',
  'Health & Wellness',
  'Pet Supplies & Care',
  'Mobile Devices & Gadgets',
  'Hobbies, Toys & Collectibles',
  'Cameras, Optics & Drones',
  'Motorcycle Parts & Gear',
  'Fashion Accessories & Jewelry',
  "Men's Apparel & Tactical Wear",
  "Women's Bags & Purses",
  "Women's Footwear",
  'Gaming Consoles & Video Games',
  "Men's Footwear",
  "Men's Bags & Tactical Backpacks",
  'Travel Gear & Luggage',
  'Audio Equipment & Headphones',
  'Books, Media & Publications',
  'Timepieces & Watches',
  'Digital Goods, Services & Subscriptions',
] as const;

export type Sals3CategoryL1 = (typeof SALS3_CATEGORY_L1_OPTIONS)[number];
